title: "Your Project"
description: "Public Seminar Series"
url: "https://rmcgranaghan.github.io"
baseurl: "/complex-risk-seminar"

collections:
  seminars:
    output: true
    permalink: /seminars/:title/

theme: minima
markdown: kramdown
