title: "Complex Risk Seminar"
description: "A public seminar series on complex risks and resilience."
url: "https://risk-seminar.ryanmcgranaghan.com"
baseurl: ""   # leave empty since it's at the root of that domain

markdown: kramdown
theme: minima

collections:
  seminars:
    output: true
    permalink: /seminars/:title/
