<<<<<<< HEAD
title: "Complex Risk Seminar"
description: "A public seminar series on complex risks and resilience."
url: "https://rmcgranaghan.github.io"
baseurl: "/complex-risk-seminar"

markdown: kramdown
theme: minima
=======
title: "Your Project"
description: "Public Seminar Series"
url: "https://rmcgranaghan.github.io"
baseurl: "/complex-risk-seminar"
>>>>>>> b3415995d30394d6790dfdd1b8d9456b8e5cf294

collections:
  seminars:
    output: true
    permalink: /seminars/:title/
